spring:
  application:
    name: pointage-api
  profiles:
    active: default
server:
  port: 8095
eureka:
  client:
    register-with-eureka: true
    serviceUrl:
      defaultZone: http://localhost:8761/eureka/
  instance:
    preferIpAddress: false
