spring:
  application:
    name: pointage-server
  profiles:
    active: default
server:
  port: 8085
eureka:
  client:
    register-with-eureka: true
    serviceUrl:
      defaultZone: http://localhost:8761/eureka/
  instance:
    preferIpAddress: false
