spring:
  application:
    name: pointage-web
  profiles:
    active: default
server:
  port: 8080
eureka:
  client:
    register-with-eureka: false
    serviceUrl:
      defaultZone: http://localhost:8761/eureka/
  instance:
    preferIpAddress: true
